# Generated by Django 5.2.7 on 2025-12-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_college',
            fields=[
                ('collegeid', models.AutoField(primary_key=True, serialize=False)),
                ('collegename', models.CharField(max_length=100)),
            ],
        ),
    ]
