# Generated by Django 5.2.7 on 2025-12-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_genre',
            fields=[
                ('genreid', models.AutoField(primary_key=True, serialize=False)),
                ('genrename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_movie',
            fields=[
                ('movieid', models.AutoField(primary_key=True, serialize=False)),
                ('moviename', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_college',
        ),
    ]
