# Generated by Django 5.2.7 on 2025-12-04 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_tbl_genre_tbl_movie_delete_tbl_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_genre',
            fields=[
                ('mgid', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_movie')),
            ],
        ),
    ]
