# Generated by Django 5.2.7 on 2026-01-05 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_movie',
            name='genreid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_genre'),
        ),
        migrations.AddField(
            model_name='tbl_movie',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='tbl_movie',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_movie',
            name='releaseyear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='movie_genre',
        ),
    ]
