# Generated by Django 5.2.7 on 2026-01-05 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_tbl_movie_description_tbl_movie_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_movie')),
            ],
        ),
    ]
