# Generated by Django 5.2.7 on 2026-01-05 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_movie_description_tbl_movie_duration_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_movie_genre',
            fields=[
                ('mgid', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_movie')),
            ],
        ),
        migrations.DeleteModel(
            name='movie_genre',
        ),
    ]
