# Generated by Django 5.2.7 on 2026-01-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_tbl_movie_genre_delete_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_language',
            fields=[
                ('languageid', models.AutoField(primary_key=True, serialize=False)),
                ('languagename', models.CharField(max_length=100)),
            ],
        ),
    ]
