# Generated by Django 5.2.7 on 2026-01-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_tbl_language_tbl_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_movie',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
