# Generated by Django 5.2.7 on 2026-01-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_tbl_movie_description_tbl_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_language',
            name='iso_639_1',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
