# Generated by Django 5.2.7 on 2026-01-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_guest',
            fields=[
                ('guestid', models.AutoField(primary_key=True, serialize=False)),
                ('guestname', models.CharField(max_length=100)),
                ('guestemail', models.CharField(max_length=100)),
            ],
        ),
    ]
