# Generated by Django 5.2.7 on 2026-01-16 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0002_tbl_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.login')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_guest',
        ),
    ]
