# Generated by Django 5.2.7 on 2026-01-16 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_tbl_movie_description_tbl_movie_duration'),
        ('guestapp', '0005_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userpreference',
            fields=[
                ('preferenceid', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(max_length=100)),
                ('genreid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_genre')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_user')),
            ],
        ),
    ]
