# Generated by Django 5.2.7 on 2026-01-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_tbl_movie_description_tbl_movie_duration'),
        ('guestapp', '0006_tbl_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_recommendationlog',
            fields=[
                ('recommendationid', models.AutoField(primary_key=True, serialize=False)),
                ('recommendeddate', models.DateField()),
                ('score', models.CharField(max_length=100)),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_movie')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_user')),
            ],
        ),
    ]
