# Generated by Django 5.2.7 on 2026-01-16 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_tbl_movie_description_tbl_movie_duration'),
        ('guestapp', '0007_tbl_recommendationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=100)),
                ('reviewtext', models.TextField()),
                ('reviewdate', models.DateField()),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_movie')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_user')),
            ],
        ),
    ]
