# Generated by Django 5.2.7 on 2026-01-22 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_tbl_movie_description_tbl_movie_duration'),
        ('guestapp', '0008_tbl_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_watchlist',
            name='movieid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_movie'),
        ),
    ]
